### ISSUE TITLE
Uncaught Error: Cannot find module "script!sql.js"

### ISSUE THREAD

**Issue by yakhinvadim** [ewnd9/anki-apkg-export#19]
I tried to fix the issue #18 by checking if window object is present. 
I added 
```
 || typeof window !== 'undefined'
```
here: https://github.com/ewnd9/anki-apkg-export/blob/master/src/index.js#L8
and here: https://github.com/ewnd9/anki-apkg-export/blob/master/src/exporter.js#L56
(but in dist folder) and it worked. But I faced an error:
![image](https://user-images.githubusercontent.com/11838280/27260360-b0ecc8ac-5432-11e7-8eb9-a9e7f8624888.png)
Unfortunately, I don't understand the cause of the error. `script` and `raw` loaders are installed. Maybe the reason is in webpack config somewhere, but can't edit it.

Do you have an idea what can cause this error and how I could fix it?

In case you'd like to try it yourself, I created a minimal representation of this case in this repo: 
https://github.com/yakhinvadim/anki-apkg-export-error
This is app, created with create-react-app. My changes for this case are in this commit https://github.com/yakhinvadim/anki-apkg-export-error/commit/4fec6c2872e17ce3afebbe1e02de1b847bc59a10

**Comment by ewnd9** [comment]
The reason behind the error is due to deprecation of short loader syntax (should be `script-loader` in `webpack@2`)

However, after manually change that, I see the following 

![image](https://user-images.githubusercontent.com/1713789/27261220-4fb72e1c-5471-11e7-8f0b-28f08a3fa031.png)

I suggest starting with the browser example from this repo and gradually add dependencies/config from ejected `create-react-app` to find what's wrong.

**Comment by yakhinvadim** [comment]
Thanks for the help. I'll try to fix it and send a PR.

**Comment by yakhinvadim** [comment]
For some reason, there are several very similar "filesaver" packages on npm (in order of popularity)

- https://www.npmjs.com/package/file-saver
- https://www.npmjs.com/package/filesaver.js
- https://www.npmjs.com/package/filesaverjs
- https://www.npmjs.com/package/file-saverjs

You are using the third one and it works fine for your cases, but its readme says to use the first. I installed it and my error has gone :)

I tried the most popular package with your examples and it doesn't work correctly for browser-media-file-input (card doesn't have the image from input). I'll send you a PR, where I switched the filesaverjs for file-saver, so if you wanted to, you could investigate why it doesn't work as expected. But it breaks your examples, so it's ok if you decline it.

I have sent a PR #22, which fixes short-loader syntax.

**Comment by ewnd9** [comment]
Yeah, I've seen deprecation messages from `filesaver` when tried your `create-react-app` example, but didn't have time to check. 

> I installed it and my error has gone :)

You are talking about the deprecate error in https://github.com/ewnd9/anki-apkg-export/issues/19#issuecomment-309279462 right?

I'm going to investigate the package from your pr later, thanks for help :+1:

**Comment by yakhinvadim** [comment]
> You are talking about the deprecate error in #19 (comment) right?

Sorry, I wasn't clear. Yes, I was talking about deprecate error.

**Comment by ewnd9** [comment]
Apparently the most popular `filesaver` wasn't on npm at the time I published the first version (package.json only added in May 26, 2016 https://github.com/eligrey/FileSaver.js/commit/cb8e076073d44a994e29dd653a02c95af2036ad5)

**Comment by ewnd9** [comment]
I've checked locally your branch and turned out you forgot to rebase with my latest changes, the error in examples was due to very old `anki-apkg-export` dependency, see https://github.com/ewnd9/anki-apkg-export/commit/cc9d68668edb24247701e079a84be9c80c0252d6

Thanks again, not only the package now is future-proof, but I also gained the knowledge about non-obvious (for me) deprecating behavior in some environments, appreciate that :v: 

---

I've published `v3.2.0`, let me know if it works ok for your project.

**Comment by yakhinvadim** [comment]
Everything's ok now, thanks!
